spring:
  data:
    mongodb:
      host: localhost
      port: 27018 # when flapdoodle using
      database: book_store

  mvc:
    hiddenmethod:
      filter:
        enabled: true

#  autoconfigure:
#    exclude: de.flapdoodle.embed.mongo.spring.autoconfigure.EmbeddedMongoAutoConfiguration

logging:
  level:
    org:
      springframework:
        security: DEBUG
        wed: DEBUG

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

