spring:

  autoconfigure:
    exclude: de.flapdoodle.embed.mongo.spring.autoconfigure.EmbeddedMongoAutoConfiguration

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
      table-prefix: public.batch_

  #  postgres
  datasource:
#    url: jdbc:h2:mem:maindb
    url: jdbc:postgresql://localhost:5432/ilnurnasibullin
  sql:
    init:
      mode: always
      schema-locations: schema.sql, drop-batch-tables.sql

  #  postgres
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #  mongo
  data:
    mongodb:
      host: localhost
      port: 27018 # when flapdoodle using
      database: book_store

  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG

#  autoconfigure:
#    exclude: de.flapdoodle.embed.mongo.spring.autoconfigure.EmbeddedMongoAutoConfiguration

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

